services:
  app:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - browser-template

  browser-template:
    build:
      context: ./docker/browser_proxy/
    ports:
      - "9221:9221"
    environment:
      - VNC_PW=password
      - RESOLUTION=1920x1080
      - APP_ARGS=--remote-debugging-port=6801 --remote-allow-origins=* --user-data-dir=remote-profile
    shm_size: 512m

volumes:
  browser-profiles:
