services:
  app:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - browser-template

  browser-template:
    image: kasmweb/brave:1.17.0-rolling-daily
    ports:
      - "6901:6901"
      - "6801:6801"
    environment:
      - VNC_PW=password
      - RESOLUTION=1920x1080
      - APP_ARGS=--remote-debugging-port=6801 -- remote-allow-origins=* --user-data-dir=remote-profile
    shm_size: 512m

volumes:
  browser-profiles:
